# Generated by Django 5.1 on 2024-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='about',
            field=models.CharField(default='This is the default about section.', max_length=500, null=True, blank=True),
            preserve_default=False,
        ),
    ]
