# Generated by Django 5.1 on 2024-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_customer_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='about',
            field=models.TextField(blank=True, default='This is the default about section.', null=True),
        ),
    ]
