# Generated by Django 5.1 on 2024-08-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_customer_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
