# Generated by Django 5.1 on 2024-08-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_customer_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='about',
        ),
    ]
